---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nop-rs
spec:
  minReadySeconds: 25
  replicas: 2
  selector:
    matchLabels:
      app: nop
  template:
    metadata:
      labels:
        app: nop
        env: dev
    spec:
      containers:
        - name: nop
          image: mrjadhav/nopcommerse:nop1
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nop-svc
spec:
  type: LoadBalancer
  selector:
    app: nop
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP