---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql-database
    engine: mysql:8.0-debian
spec:
  containers:
    - name: mysql
      image: mysql:8.0-debian
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin@1234
        - name: MYSQL_DATABASE
          value: mysql-db
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin@1234
      resources:
        limits:
          memory: "256Mi"
          cpu: "0.5"
      ports:
        - containerPort: 3306

