---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: front-end
  labels:
    app: fe
    topic: replicaset
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
        topic: pod
    spec:
      containers:
        - name: fe-cont
          image: nginx
          ports:
            - containerPort: 80